import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/HomePage/Hero'
import PopularHome from '../components/Products/PopularHome';
import ProductCard from '../components/Products/ProductCard';
import styles from '../styles/Home.module.css'
import { axiosFetch } from '../utils/axiosFetch'

export default function Home(props) {
  // console.log(props.products);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <main className={`${styles.mainPageHero}`}>

        <section className='max-w-[800px] m-auto'>
          <Hero />

        </section>


      </main>

      <PopularHome />

    </>
  )
}

// export async function getServerSideProps(context) {
//   console.log("server side");
//   const gql = String.raw;

//   const query = gql`
//     query Products {
//       products(first: 3) {
//         edges {
//           node {
//             createdAt
//             title
//             handle
//             tags
//             priceRange {
//               minVariantPrice {
//                 amount
//               }
//             }
//             images(first: 1) {
//               edges {
//                 node {
//                   url
//                   altText
//                 }
//               }
//             }
//           }
//         }
//       }
//     }
//   `;
//   // const fetch = axiosFetch;
//   const res = await axiosFetch("SHOPIFY_QUERY", query);

//   const products = await res.data.data.products.edges.map((product) => {
//     let objProduct = {
//       id: product.node.createdAt,
//       title: product.node.title,
//       handle: product.node.handle,
//       tags: product.node.handle,
//       priceRange: product.node.priceRange.minVariantPrice.amount,
//       images: product.node.images.edges[0].node,
//     }
//     // console.log(product.node.images.edges[0].node);
//     return objProduct
//   }
//   );
//   // console.log(res.data);
//   return {
//     props: { products }, // will be passed to the page component as props
//   };
// }


